### ISSUE TITLE
How can I finish effect as shown in figure? A video recording, add a separate line.

### ISSUE THREAD

**Issue by xhzengAIB** [subjc/SparkRecordingCircle#1]
Hi! @sampage  @subjc 
like the picture:
![b932faf0-c419-449b-8cc2-39043390a10a](https://f.cloud.github.com/assets/1969908/2300844/4edab312-a10d-11e3-82cc-97febfb93449.png)
![de11fa8b-1153-45ce-b1af-2dc2af6ff004](https://f.cloud.github.com/assets/1969908/2300845/5d4ff330-a10d-11e3-86d4-36767a7e6e8e.png)

like the Instagram App multiple video recodering bar.

Jack

**Comment by sampage** [comment]
Hey Jack, I'm not sure exactly what you're after but I would guess that using CAShapeLayer's would achieve this for you. 

Have a look at the <code>RecordingCircleOverlayView</code> class in this repo for an idea of how this might work. You would likely just need to modify the path to be a straight line rather than an arc/circle.

**Comment by xhzengAIB** [comment]
Hi! @sampage 
How should I do? Can you give an example? I technology is not good enough.
Jack

**Comment by sampage** [comment]
Hey Jack, have a read through this post http://subjc.com/spark-camera. It details how to accomplish a similar view (using circles rather than straight lines) and it should translate to what you're looking for. This repo contains the full sample project for the post.

**Comment by xhzengAIB** [comment]
@sampage 
Wow, very beautiful and tidy. Ok, I see your articles, thanks you for your help.

Jack

**Comment by sampage** [comment]
I should've included a README for this project, my mistake :) Hope you get some use out of the code/articles.

**Comment by xhzengAIB** [comment]
thanks you
